Aggregate Opportunity
rbignon/doctoshotgun pull request #107
Opened 2021-07-20 18:13 UTC by HalimaSalifu

I updated what I had forked to my repository in order to identify possible ways to aggregate methods. I have done so in order to show the similar methods and place together.

2021-07-20 19:32 UTC, gitolicious requested changes
You indentation looks weird as you don't indent the content of classes. Also there are quire a few empty lines which Prettier will help you get rid off.

2021-07-20 19:32 UTC, gitolicious commented on doctoshotgun.py
> +    ''' Place all instances of booking an appointment in one place '''
Compilation fails at this line, please double-check
> IndentationError: expected an indented block

2021-07-20 19:32 UTC, gitolicious commented on doctoshotgun.py
> +
Please run [Prettier](https://prettier.io/) before committing so we keep a consistent code format.

2021-07-22 08:40 UTC, rbignon commented
Hello,

I appreciate your contribution, but please tell your teacher to ask you to contribute to opensource softwares with useful features, not by applying a design pattern with your brain turned off.

Thank you.

2021-07-22 08:40 UTC, closed without merging