Select patient with command line arguments (limit user interaction)
rbignon/doctoshotgun pull request #28
Opened 2021-05-21 13:53 UTC by cvermot

Give patient ID as argument.

2021-05-21 14:11 UTC, nicogodet commented on README.md
> +$ ./doctoshotgun.py paris roger.philibert@gmail.com PASSWORD - p 1
```suggestion
$ ./doctoshotgun.py paris roger.philibert@gmail.com PASSWORD -p 1
```

2021-05-21 14:13 UTC, cvermot commented
Thank you !

2021-05-22 08:28 UTC, rbignon requested changes
Hello,

Thank you for your contribution. Can you rebase on master and remove commits not related to this PR?

2021-05-22 08:28 UTC, rbignon commented on doctoshotgun.py
> +        #log(args.patient)
You can remove this line

2021-05-22 08:28 UTC, rbignon commented on doctoshotgun.py
> +        return normalized.lower()
Not related to this PR

2021-05-22 08:28 UTC, rbignon commented on doctoshotgun.py
> +                if docto.normalize(center['city']) not in cities:
Not related to this PR

2021-05-22 08:28 UTC, rbignon commented on README.md
> +You want to book a slot for whom patient?
The wording has changed since last commit :)

2021-05-22 17:21 UTC, cvermot commented
Should be fine now ! Thank you for reviewing.

2021-05-23 11:17 UTC, merged